import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "AI Voice Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid vh-100 d-flex flex-column">
          

          {/* Main Content */}
          <div className="row flex-grow-1">
            {/* Sidebar */}
            <aside className="col-12 col-md-3 col-lg-2 bg-light border-end py-4">
              {/* Header */}
              <header className="bg-light py-2 px-3 ">
                <h1 className="fs-4 m-0 fw-bold">JARVIS</h1>
              </header>
              <ul className="nav flex-column">
                <li className="nav-item">
                  <Link href="/" className="nav-link text-decoration-none text-reset">
                    Home
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/text-to-speech" className="nav-link text-decoration-none text-reset">
                    Text to Speech
                  </Link>
                </li>
              </ul>
            </aside>

            {/* Main Content */}
            <main className="col-12 col-md-9 col-lg-10 m-0 p-0">
              {children}
            </main>
          </div>

          {/* Footer */}
          <footer className="bg-light py-3 px-4 border-top text-center">
            <p className="m-0">Developed by Walton & Guillermo</p>
          </footer>
        </div>
      </body>
    </html>
  );
}